variables:
  DAS6_MODULES: "spack/20250109 cmake cuda"

stages:
  - linting
  - build
  - test

format:
  stage: linting
  image: ubuntu:22.04
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq git python3-pip
    - pip3 install clang-format==14.0.0 cmake-format pre-commit
  script:
    - pre-commit run -a

build-das6-cuda:
  stage: build
  tags:
    - das6-gpu
  before_script:
    - module load ${DAS6_MODULES}
  script:
    - cmake -S . -B build
    - make -j -C build

build-das6-hip:
  stage: build
  tags:
    - das6-gpu
  before_script:
    - module load ${DAS6_MODULES}
  script:
    - cmake -S . -B build -DCCGLIB_BACKEND=HIP
    - make -j -C build

test-das6:
  stage: test
  tags:
    - das6-gpu
  before_script:
    - module load ${DAS6_MODULES}
  script:
    - cmake -S . -B build -DCCGLIB_BUILD_TESTING=1
    - make -j -C build
    - cd build && compute-sanitizer --tool=racecheck --error-exitcode 1 --target-processes all ctest --output-on-failure

test-das6-integration:
  stage: test
  tags:
    - das6-gpu
  before_script:
    - module load ${DAS6_MODULES}
  script:
    - cmake -S example -B build -DCCGLIB_GIT_REVISION=${CI_COMMIT_SHA}
    - make -C build
    - $(pwd)/build/example