name: Build in HIP mode

on:
  push:
  workflow_dispatch:

jobs:
  build_hip:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install HIP
        uses: loostrum/rocm-installer@main
        with:
          version: 6.4.0
          packages: rocm-hip-runtime-dev hipfft-dev

      - name: Build
        run: |
          cmake -S . -B build -DCCGLIB_BACKEND=HIP -DCCGLIB_BUILD_TESTING=1
          make -C build -j
