name: linting

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    name: linting
    runs-on: [docker]
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install linting tool
        run: |
          apt-get update -qq
          apt-get install -y -qq git python3-pip
          pip install pre-commit
          pre-commit install
          
      - name: Run linter
        run: pre-commit run -a
