name: test-cuda

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-ad4000:
    name: NVIDIA AD4000
    runs-on: [slurm]
    steps:
      - uses: actions/checkout@v4
      - uses: astron-rd/slurm-action@v1.1
        with:
          partition: fatq
          gres: gpu:AD4000
          time: "00:10:00"
          commands: |
            module load spack/20250403
            module load cuda
            cmake -S . -B build -DCCGLIB_BUILD_TESTING=1
            make -C build -j
            cd build
            ctest --output-on-failure
