name: test-hip

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-w7700:
    name: AMD W7700
    runs-on: [slurm]
    steps:
      - uses: actions/checkout@v4
      - uses: astron-rd/slurm-action@v1.1
        with:
          partition: defq
          gres: gpu:W7700
          time: "00:10:00"
          commands: |
            CXX=hipcc PATH=$PATH:/opt/rocm/bin cmake -S . -B build -DCCGLIB_BUILD_TESTING=1 -DCCGLIB_BACKEND=HIP
            make -C build -j
            cd build
            ctest --output-on-failure
